name: Checkered Board Buttons CI/CD

on:
  push:
    branches: [ main ]
    paths: 
      - 'checkered-board-buttons/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'checkered-board-buttons/**'

defaults:
  run:
    working-directory: checkered-board-buttons

jobs:
  test-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'checkered-board-buttons/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run linting
      run: npm run lint
      
    - name: Run unit tests
      run: npm run test:run
      
    - name: Build application
      run: npm run build
      
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: checkered-board-buttons/dist/
        retention-days: 7

  deploy-preview:
    runs-on: ubuntu-latest
    needs: [test-and-build]
    if: github.event_name == 'pull_request'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'checkered-board-buttons/package-lock.json'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build application
      run: npm run build
      
    - name: Deploy to GitHub Pages (Preview)
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: checkered-board-buttons/dist
        destination_dir: preview/checkered-board-buttons
        
    - name: Comment PR with preview link
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: '**Preview deployed!** \n\nCheckered Board Buttons: https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/preview/checkered-board-buttons/'
          })