name: FastAPI WebSockets Chat CI/CD

on:
  push:
    branches: [ main ]
    paths: 
      - 'fastapi-websockets-chat/**'
  pull_request:
    branches: [ main ]
    paths: 
      - 'fastapi-websockets-chat/**'

defaults:
  run:
    working-directory: fastapi-websockets-chat

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'fastapi-websockets-chat/package-lock.json'
        
    - name: Install frontend dependencies
      run: npm ci
      
    - name: Run frontend tests
      run: npm run test:run
      
    - name: Build frontend
      run: npm run build

  test-backend:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install backend dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Run backend tests
      run: |
        python -m pytest tests/backend/ -v

  test-e2e:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: 'fastapi-websockets-chat/package-lock.json'
        
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        
    - name: Install dependencies
      run: |
        npm ci
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Build frontend
      run: npm run build
      
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
      
    - name: Start backend server
      run: |
        python -m uvicorn backend.main:app --host 127.0.0.1 --port 8000 &
        sleep 5
        curl -f http://127.0.0.1:8000/health || exit 1
        
    - name: Run E2E tests
      run: npm run test:e2e
      
    - name: Upload Playwright report
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: playwright-report
        path: fastapi-websockets-chat/playwright-report/
        retention-days: 7

  docker-build:
    runs-on: ubuntu-latest
    needs: [test-frontend, test-backend, test-e2e]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Build Docker image
      run: |
        docker build -t fastapi-websockets-chat .
        
    - name: Test Docker image
      run: |
        docker run --rm -d -p 8000:8000 --name test-container fastapi-websockets-chat
        sleep 10
        curl -f http://localhost:8000/health || exit 1
        docker stop test-container